"""Email notification service via SMTP."""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional

from app.config import settings


async def send_email(
    to_emails: list[str],
    subject: str,
    body_html: str,
    body_text: Optional[str] = None,
) -> dict:
    """Send an email notification.

    Uses SMTP settings from config (or defaults).

    Returns:
        dict: {success: bool, error: str|None}
    """
    smtp_host = getattr(settings, "smtp_host", "localhost")
    smtp_port = getattr(settings, "smtp_port", 587)
    smtp_user = getattr(settings, "smtp_user", "")
    smtp_password = getattr(settings, "smtp_password", "")
    smtp_from = getattr(settings, "smtp_from", "noreply@bluecircle.org")
    smtp_use_tls = getattr(settings, "smtp_use_tls", True)

    if not to_emails:
        return {"success": False, "error": "No recipients"}

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[Blue Circle] {subject}"
        msg["From"] = smtp_from
        msg["To"] = ", ".join(to_emails)

        if body_text:
            msg.attach(MIMEText(body_text, "plain", "utf-8"))
        msg.attach(MIMEText(body_html, "html", "utf-8"))

        if smtp_use_tls:
            context = ssl.create_default_context()
            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                server.starttls(context=context)
                if smtp_user:
                    server.login(smtp_user, smtp_password)
                server.sendmail(smtp_from, to_emails, msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                if smtp_user:
                    server.login(smtp_user, smtp_password)
                server.sendmail(smtp_from, to_emails, msg.as_string())

        return {"success": True, "error": None}

    except Exception as e:
        return {"success": False, "error": str(e)[:300]}


def build_alert_email_html(alert_type: str, severity: str, title: str, description: str,
                           turtle_id: str = None, turtle_name: str = None,
                           lat: float = None, lng: float = None) -> str:
    """Build a nice HTML email for an alert notification."""
    sev_colors = {
        "critical": "#ef4444",
        "high": "#f09040",
        "medium": "#f0c040",
        "low": "#60d060",
    }
    sev_color = sev_colors.get(severity, "#94a3b8")

    turtle_info = ""
    if turtle_id:
        turtle_info = f"<p><strong>海龟/Turtle:</strong> {turtle_name or turtle_id} ({turtle_id})</p>"
        if lat and lng:
            turtle_info += f"<p><strong>位置/Position:</strong> {lat:.4f}, {lng:.4f}</p>"

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;background:#0a1628;color:#e0e8f0;padding:24px">
<div style="max-width:600px;margin:0 auto;background:#0f1f38;border-radius:8px;overflow:hidden">
  <div style="background:linear-gradient(135deg,#1a3a5c,#0d2847);padding:24px;border-bottom:3px solid {sev_color}">
    <h1 style="color:#fff;margin:0;font-size:20px">🔔 Blue Circle 预警通知</h1>
    <p style="color:#6b9fd4;margin:4px 0 0">Alert Notification</p>
  </div>
  <div style="padding:24px">
    <div style="background:#152a45;border-radius:6px;padding:16px;margin-bottom:16px">
      <span style="display:inline-block;background:{sev_color};color:#fff;padding:2px 12px;border-radius:10px;font-size:12px;font-weight:bold">{severity.upper()}</span>
      <span style="display:inline-block;background:#1a3050;color:#94a3b8;padding:2px 12px;border-radius:10px;font-size:12px;margin-left:8px">{alert_type}</span>
      <h2 style="color:#e0e8f0;margin:12px 0 8px;font-size:18px">{title}</h2>
      <p style="color:#94a3b8;line-height:1.6">{description or '—'}</p>
    </div>
    {turtle_info}
    <hr style="border:none;border-top:1px solid #1a3050;margin:16px 0">
    <p style="color:#4a6a8a;font-size:12px">
      This alert was generated by Blue Circle Turtle Tracking Platform.<br>
      <a href="https://data.maskcube.com/" style="color:#2d8cf0">View Dashboard →</a>
    </p>
  </div>
</div>
</body>
</html>"""
