"""Report generation engine — queries DB and builds HTML reports."""

from datetime import datetime, timezone
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, text

from app.models.turtle import Turtle
from app.models.track_point import TrackPoint
from app.models.alert import Alert
from app.models.report import Report


async def generate_report(
    db: AsyncSession,
    report: Report,
) -> Report:
    """Generate HTML content for a report based on its type and params."""
    report.status = "generating"

    try:
        if report.report_type == "turtle_activity":
            report.html_content = await _gen_turtle_activity(db, report)
        elif report.report_type == "fleet_overview":
            report.html_content = await _gen_fleet_overview(db, report)
        elif report.report_type == "monthly_summary":
            report.html_content = await _gen_monthly_summary(db, report)
        elif report.report_type == "alert_summary":
            report.html_content = await _gen_alert_summary(db, report)
        else:
            report.html_content = _error_html(f"Unknown report type: {report.report_type}")
            report.status = "failed"
            return report

        report.status = "completed"
        report.completed_at = datetime.now(timezone.utc)
    except Exception as e:
        report.html_content = _error_html(f"Generation failed: {str(e)}")
        report.status = "failed"

    return report


def _page_wrap(title: str, body: str, subtitle: str = "") -> str:
    """Wrap content in a clean HTML page with Blue Circle branding."""
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — Blue Circle</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background:#0a1628; color:#e0e8f0; padding:40px; line-height:1.7; }}
  .report {{ max-width:900px; margin:0 auto; background:#0f1f38; border-radius:12px;
             border:1px solid #1a3050; overflow:hidden; }}
  .header {{ background:linear-gradient(135deg, #1a3a5c, #0d2847); padding:32px 40px;
             border-bottom:3px solid #2d8cf0; }}
  .header h1 {{ color:#fff; font-size:24px; margin-bottom:4px; }}
  .header .sub {{ color:#6b9fd4; font-size:14px; }}
  .body {{ padding:32px 40px; }}
  .footer {{ padding:20px 40px; border-top:1px solid #1a3050; color:#4a6a8a; font-size:12px; }}
  h2 {{ color:#2d8cf0; font-size:18px; margin:24px 0 12px; border-bottom:1px solid #1a3050; padding-bottom:8px; }}
  h2:first-child {{ margin-top:0; }}
  table {{ width:100%; border-collapse:collapse; margin:12px 0; }}
  th {{ background:#152a45; color:#6b9fd4; padding:10px 12px; text-align:left; font-size:13px; }}
  td {{ padding:10px 12px; border-bottom:1px solid #152a45; font-size:14px; }}
  tr:hover td {{ background:#152a45; }}
  .stat-card {{ display:inline-block; background:#152a45; border-radius:8px; padding:16px 24px;
                margin:6px 8px 6px 0; min-width:140px; text-align:center; }}
  .stat-card .value {{ font-size:28px; font-weight:bold; color:#2d8cf0; }}
  .stat-card .label {{ font-size:12px; color:#6b9fd4; margin-top:4px; }}
  .badge {{ display:inline-block; padding:2px 10px; border-radius:10px; font-size:12px; }}
  .badge-critical {{ background:#4a1a1a; color:#f06060; }}
  .badge-high {{ background:#4a2a1a; color:#f09040; }}
  .badge-medium {{ background:#3a3a1a; color:#f0c040; }}
  .badge-low {{ background:#1a3a1a; color:#60d060; }}
  .no-data {{ color:#4a6a8a; font-style:italic; padding:20px; text-align:center; }}
  .divider {{ border:none; border-top:1px solid #1a3050; margin:24px 0; }}
</style>
</head>
<body>
<div class="report">
  <div class="header">
    <h1>{title}</h1>
    <div class="sub">{subtitle}</div>
  </div>
  <div class="body">
{body}
  </div>
  <div class="footer">
    Generated by Blue Circle 海龟追踪平台 &middot; {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
  </div>
</div>
</body>
</html>"""


def _error_html(msg: str) -> str:
    return _page_wrap("Report Error", f'<p style="color:#f06060;">⚠ {msg}</p>')


# ── Report type generators ──

async def _gen_turtle_activity(db: AsyncSession, report: Report) -> str:
    """Generate a single-turtle activity report."""
    turtle_id = report.turtle_id or (report.params or {}).get("turtle_id", "")
    if not turtle_id:
        return _error_html("No turtle_id specified for turtle_activity report")

    # Fetch turtle
    result = await db.execute(select(Turtle).where(Turtle.id == turtle_id))
    turtle = result.scalar()
    if not turtle:
        return _error_html(f"Turtle {turtle_id} not found")

    # Fetch track points
    date_from = (report.params or {}).get("date_from")
    date_to = (report.params or {}).get("date_to")
    tp_q = select(TrackPoint).where(TrackPoint.turtle_id == turtle_id)
    if date_from:
        tp_q = tp_q.where(TrackPoint.time >= date_from)
    if date_to:
        tp_q = tp_q.where(TrackPoint.time <= date_to)
    tp_q = tp_q.order_by(TrackPoint.time.desc()).limit(500)
    tp_result = await db.execute(tp_q)
    track_points = tp_result.scalars().all()

    # Stats
    total_points = len(track_points)
    if track_points:
        speeds = [tp.speed_kmh for tp in track_points if tp.speed_kmh is not None]
        depths = [tp.depth_m for tp in track_points if tp.depth_m is not None]
        temps = [tp.temperature_c for tp in track_points if tp.temperature_c is not None]
        avg_speed = sum(speeds) / len(speeds) if speeds else 0
        avg_depth = sum(depths) / len(depths) if depths else 0
        avg_temp = sum(temps) / len(temps) if temps else 0
        max_speed = max(speeds) if speeds else 0
        max_depth = max(depths) if depths else 0
        first_seen = track_points[-1].time if track_points else None
        last_seen = track_points[0].time if track_points else None
    else:
        avg_speed = avg_depth = avg_temp = max_speed = max_depth = 0
        first_seen = last_seen = None

    # Alerts
    alert_q = select(func.count()).where(
        Alert.turtle_id == turtle_id
    )
    alert_total = (await db.execute(alert_q)).scalar() or 0
    alert_open_q = select(func.count()).where(
        Alert.turtle_id == turtle_id, Alert.status == "open"
    )
    alert_open = (await db.execute(alert_open_q)).scalar() or 0

    # Build stats cards
    stats_html = f"""
<div style="margin-bottom:20px;">
  <div class="stat-card"><div class="value">{total_points}</div><div class="label">轨迹点</div></div>
  <div class="stat-card"><div class="value">{avg_speed:.1f}</div><div class="label">平均速度 (km/h)</div></div>
  <div class="stat-card"><div class="value">{avg_depth:.1f}</div><div class="label">平均深度 (m)</div></div>
  <div class="stat-card"><div class="value">{avg_temp:.1f}°C</div><div class="label">平均水温</div></div>
  <div class="stat-card"><div class="value">{max_speed:.1f}</div><div class="label">最大速度 (km/h)</div></div>
  <div class="stat-card"><div class="value">{max_depth:.1f}</div><div class="label">最大深度 (m)</div></div>
  <div class="stat-card"><div class="value">{alert_open}</div><div class="label">活跃预警</div></div>
</div>"""

    # Turtle info table
    info_html = f"""
<h2>🐢 海龟信息</h2>
<table>
  <tr><th width="140">ID</th><td>{turtle.id}</td></tr>
  <tr><th>名称</th><td>{turtle.name} ({turtle.name_en or '—'})</td></tr>
  <tr><th>物种</th><td>{turtle.species} ({turtle.species_en or '—'})</td></tr>
  <tr><th>性别</th><td>{turtle.sex or '未知'}</td></tr>
  <tr><th>来源地</th><td>{turtle.origin or '—'}</td></tr>
  <tr><th>甲长</th><td>{f'{turtle.carapace_length_cm} cm' if turtle.carapace_length_cm else '—'}</td></tr>
  <tr><th>最新位置</th><td>{f'{turtle.last_lat:.4f}, {turtle.last_lng:.4f}' if turtle.last_lat else '—'}</td></tr>
  <tr><th>设备电量</th><td>{f'{turtle.last_battery_pct}%' if turtle.last_battery_pct else '—'}</td></tr>
  <tr><th>风险等级</th><td>{turtle.risk_level or '—'}</td></tr>
  <tr><th>预警总数</th><td>{alert_total}（活跃: {alert_open}）</td></tr>
</table>"""

    # Track summary
    if track_points:
        rows = []
        for tp in track_points[:20]:
            time_str = tp.time.strftime("%Y-%m-%d %H:%M") if tp.time else "—"
            speed_str = f"{tp.speed_kmh:.1f}" if tp.speed_kmh else "—"
            depth_str = f"{tp.depth_m:.1f}" if tp.depth_m else "—"
            temp_str = f"{tp.temperature_c:.1f}" if tp.temperature_c else "—"
            rows.append(
                f"<tr><td>{time_str}</td>"
                f"<td>{tp.lat:.4f}, {tp.lng:.4f}</td>"
                f"<td>{speed_str}</td>"
                f"<td>{depth_str}</td>"
                f"<td>{temp_str}°C</td></tr>"
            )
        tracks_html = f"""
<h2>📍 最近轨迹（前 20 条，共 {total_points}）</h2>
<table>
  <tr><th>时间</th><th>坐标</th><th>速度</th><th>深度</th><th>水温</th></tr>
  {''.join(rows)}
</table>"""
    else:
        tracks_html = '<h2>📍 最近轨迹</h2><p class="no-data">暂无轨迹数据</p>'

    period = ""
    if date_from or date_to:
        period = f" ({date_from or '开始'} ~ {date_to or '至今'})"

    return _page_wrap(
        f"海龟活动报告: {turtle.name}",
        stats_html + info_html + tracks_html,
        f"Report ID: {report.id} &middot; {turtle.species}{period}",
    )


async def _gen_fleet_overview(db: AsyncSession, report: Report) -> str:
    """Generate fleet overview — all turtles summary."""
    result = await db.execute(select(Turtle).order_by(Turtle.id))
    turtles = result.scalars().all()

    # Total stats
    total_turtles = len(turtles)
    active_turtles = sum(1 for t in turtles if t.is_active)
    species_set = set(t.species for t in turtles)

    # Track point counts
    tp_result = await db.execute(
        select(func.count()).select_from(TrackPoint)
    )
    total_tracks = tp_result.scalar() or 0

    # Alert stats
    alert_result = await db.execute(
        select(func.count(Alert.id))
    )
    total_alerts = alert_result.scalar() or 0
    open_alerts_result = await db.execute(
        select(func.count(Alert.id)).where(Alert.status == "open")
    )
    open_alerts = open_alerts_result.scalar() or 0

    stats_html = f"""
<div style="margin-bottom:20px;">
  <div class="stat-card"><div class="value">{total_turtles}</div><div class="label">海龟总数</div></div>
  <div class="stat-card"><div class="value">{active_turtles}</div><div class="label">活跃海龟</div></div>
  <div class="stat-card"><div class="value">{len(species_set)}</div><div class="label">物种数</div></div>
  <div class="stat-card"><div class="value">{total_tracks:,}</div><div class="label">轨迹总点数</div></div>
  <div class="stat-card"><div class="value">{total_alerts}</div><div class="label">预警总数</div></div>
  <div class="stat-card"><div class="value">{open_alerts}</div><div class="label">活跃预警</div></div>
</div>"""

    # Turtle list table
    rows = []
    for t in turtles:
        pos_str = f"{t.last_lat:.2f}, {t.last_lng:.2f}" if t.last_lat else "—"
        bat_str = f"{t.last_battery_pct}%" if t.last_battery_pct else "—"
        rows.append(
            f"<tr>"
            f"<td><strong>{t.id}</strong></td>"
            f"<td>{t.name}</td>"
            f"<td>{t.species}</td>"
            f"<td>{t.sex or '—'}</td>"
            f"<td>{t.origin or '—'}</td>"
            f"<td>{pos_str}</td>"
            f"<td>{bat_str}</td>"
            f"<td>{'🟢' if t.is_active else '🔴'}</td>"
            f"</tr>"
        )

    fleet_html = f"""
<h2>🐢 海龟舰队</h2>
<table>
  <tr><th>ID</th><th>名称</th><th>物种</th><th>性别</th><th>来源地</th><th>最后位置</th><th>电量</th><th>状态</th></tr>
  {''.join(rows)}
</table>"""

    return _page_wrap(
        "舰队总览报告",
        stats_html + fleet_html,
        f"共 {total_turtles} 只海龟 &middot; {len(species_set)} 个物种",
    )


async def _gen_monthly_summary(db: AsyncSession, report: Report) -> str:
    """Generate monthly conservation summary."""
    from datetime import datetime as dt

    date_from = (report.params or {}).get("date_from", "")
    date_to = (report.params or {}).get("date_to", "")

    # Parse dates safely
    dt_from = None
    dt_to = None
    if date_from:
        try:
            dt_from = dt.fromisoformat(date_from)
        except (ValueError, TypeError):
            dt_from = None
    if date_to:
        try:
            dt_to = dt.fromisoformat(date_to)
        except (ValueError, TypeError):
            dt_to = None

    # Turtles
    result = await db.execute(select(func.count(Turtle.id)))
    turtle_count = result.scalar() or 0

    # New tracks in period
    tp_q = select(func.count()).select_from(TrackPoint)
    if dt_from:
        tp_q = tp_q.where(TrackPoint.time >= dt_from)
    if dt_to:
        tp_q = tp_q.where(TrackPoint.time <= dt_to)
    tp_result = await db.execute(tp_q)
    new_tracks = tp_result.scalar() or 0

    # Alerts in period
    alert_q = select(func.count(Alert.id))
    if dt_from:
        alert_q = alert_q.where(Alert.created_at >= dt_from)
    if dt_to:
        alert_q = alert_q.where(Alert.created_at <= dt_to)
    alert_result = await db.execute(alert_q)
    period_alerts = alert_result.scalar() or 0

    # Resolved alerts
    resolved_q = select(func.count(Alert.id)).where(Alert.status == "resolved")
    if dt_from:
        resolved_q = resolved_q.where(Alert.resolved_at >= dt_from)
    if dt_to:
        resolved_q = resolved_q.where(Alert.resolved_at <= dt_to)
    resolved_result = await db.execute(resolved_q)
    resolved_count = resolved_result.scalar() or 0

    period_str = f"{date_from} ~ {date_to}" if date_from or date_to else "所有时间"

    return _page_wrap(
        "月度保育摘要报告",
        f"""
<div style="margin-bottom:20px;">
  <div class="stat-card"><div class="value">{turtle_count}</div><div class="label">追踪中海龟</div></div>
  <div class="stat-card"><div class="value">{new_tracks:,}</div><div class="label">新增轨迹点</div></div>
  <div class="stat-card"><div class="value">{period_alerts}</div><div class="label">期间预警</div></div>
  <div class="stat-card"><div class="value">{resolved_count}</div><div class="label">已解决预警</div></div>
</div>

<h2>📋 保育摘要</h2>
<table>
  <tr><th width="180">统计周期</th><td>{period_str}</td></tr>
  <tr><th>追踪海龟数</th><td>{turtle_count} 只</td></tr>
  <tr><th>新增轨迹数据</th><td>{new_tracks:,} 个定位点</td></tr>
  <tr><th>期间预警</th><td>{period_alerts} 条</td></tr>
  <tr><th>已解决预警</th><td>{resolved_count} 条</td></tr>
  <tr><th>解决率</th><td>{f'{resolved_count / period_alerts * 100:.0f}%' if period_alerts else 'N/A'}</td></tr>
</table>

<p style="margin-top:24px; color:#6b9fd4;">
  📝 本报告由 Blue Circle 海龟追踪平台自动生成。如需详细数据，请访问
  <a href="https://data.maskcube.com/" style="color:#2d8cf0;">data.maskcube.com</a>。
</p>""",
        f"统计周期: {period_str}",
    )


async def _gen_alert_summary(db: AsyncSession, report: Report) -> str:
    """Generate alert statistics report."""
    # Per severity
    sev_rows = []
    for sev in ["critical", "high", "medium", "low"]:
        result = await db.execute(
            select(func.count(Alert.id)).where(Alert.severity == sev)
        )
        count = result.scalar() or 0
        open_result = await db.execute(
            select(func.count(Alert.id)).where(
                Alert.severity == sev, Alert.status == "open"
            )
        )
        open_count = open_result.scalar() or 0
        badge_class = f"badge-{sev}"
        sev_rows.append(
            f"<tr><td><span class='badge {badge_class}'>{sev.upper()}</span></td>"
            f"<td>{count}</td><td>{open_count}</td></tr>"
        )

    # Per type
    type_q = await db.execute(
        select(Alert.alert_type, func.count(Alert.id))
        .group_by(Alert.alert_type)
        .order_by(func.count(Alert.id).desc())
    )
    type_rows = []
    for alert_type, count in type_q.all():
        type_rows.append(f"<tr><td>{alert_type}</td><td>{count}</td></tr>")

    # Top turtles with alerts
    top_q = await db.execute(
        select(Alert.turtle_id, func.count(Alert.id))
        .where(Alert.turtle_id.isnot(None))
        .group_by(Alert.turtle_id)
        .order_by(func.count(Alert.id).desc())
        .limit(10)
    )
    top_rows = []
    for tid, count in top_q.all():
        top_rows.append(f"<tr><td>{tid}</td><td>{count}</td></tr>")

    return _page_wrap(
        "预警统计报告",
        f"""
<h2>🔴 按严重程度</h2>
<table>
  <tr><th>级别</th><th>总数</th><th>活跃</th></tr>
  {''.join(sev_rows)}
</table>

<h2>📂 按类型</h2>
<table>
  <tr><th>预警类型</th><th>数量</th></tr>
  {''.join(type_rows) if type_rows else '<tr><td colspan="2" class="no-data">暂无预警</td></tr>'}
</table>

<h2>🐢 预警最多的海龟 (Top 10)</h2>
<table>
  <tr><th>海龟 ID</th><th>预警数</th></tr>
  {''.join(top_rows) if top_rows else '<tr><td colspan="2" class="no-data">暂无数据</td></tr>'}
</table>""",
        "Alert Statistics Report",
    )
